import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [githubData, setGithubData] = React.useState(null)

  React.useEffect(() => {
    fetch('/api/githubCore?organisation=zurichat')
      .then(response => response.json())
      .then(data => setGithubData(data))
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>ZuriChat PR Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a
            href="https://zuri.chat"
            target={'_blank'}
            rel={'noopener noreferrer'}
          >
            ZuriChat PR Tracker
          </a>
        </h1>

        <h2 style={{ textAlign: "center" }}>
          Total Number Of PRs Closed : {githubData ? githubData.total_number_of_closed_prs : '...'}
        </h2>

        <br />

        <div className={styles.grid}>
          {githubData && githubData.data.map((item, index) => {
            return (
              <a
                key={index}
                href={item.url}
                className={styles.card}
                target={'_blank'}
                rel={'noopener noreferrer'}
              >
                <h2>{item.name} &rarr; {item.number_of_closed_prs}</h2>
                <p>{item.description}</p>
              </a>
            )
          })}
        </div>
      </main>
    </div>
  )
}
